all: float_add float_mul double_add double_mul

float_add: float_add.c
	gcc float_add.c -o float_add

float_mul: float_mul.c
	gcc float_mul.c -o float_mul

double_add: double_add.c
	gcc double_add.c -o double_add

double_mul: double_mul.c
	gcc double_mul.c -o double_mul

clean:
	rm float_add float_mul double_add double_mul
